// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_multi.Models;

namespace proyectomulti.Migrations
{
    [DbContext(typeof(SostenibilidadContext))]
    [Migration("20181031214212_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("proyecto_multi.Models.camp_usuario", b =>
                {
                    b.Property<int>("UsuarioId");

                    b.Property<int>("CampañaId");

                    b.Property<int>("montoDonacion");

                    b.HasKey("UsuarioId", "CampañaId");

                    b.HasIndex("CampañaId");

                    b.ToTable("camp_usuario");
                });

            modelBuilder.Entity("proyecto_multi.Models.Campaña", b =>
                {
                    b.Property<int>("CampañaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CantidadPersonas");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("distrito")
                        .IsRequired();

                    b.Property<string>("distrito_pro");

                    b.Property<int>("edad_min");

                    b.Property<string>("implementos");

                    b.Property<string>("informacion")
                        .IsRequired();

                    b.HasKey("CampañaId");

                    b.ToTable("Campaña");
                });

            modelBuilder.Entity("proyecto_multi.Models.usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<int>("Edad");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("celular");

                    b.Property<string>("distrito")
                        .IsRequired();

                    b.HasKey("UsuarioId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("proyecto_multi.Models.camp_usuario", b =>
                {
                    b.HasOne("proyecto_multi.Models.Campaña", "Campaña")
                        .WithMany("camp_usuarios")
                        .HasForeignKey("CampañaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("proyecto_multi.Models.usuario", "usuario")
                        .WithMany("camp_usuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
